### PR TITLE
Macos Support

### PR DESCRIPTION
**Pull request by EncinitasMechanic**

### CODE REVIEW

**Comment by newAM** [comment]
Got some of the CI functional, but bindgen seems to be non-functional.

Were there any more files in that DMG from the vendor?  Are you able to upload a zip of the contents?

There should be a `WinTypes.h` in there.
I tried some cross platform utilities to read the DMG, but I got gibberish :/

**Comment by EncinitasMechanic** [comment]
I uploaded the file in a zip called ftdi_files.zip.  Honestly, i crated the bindings with the bindgen command line tool, and didn't try the built in option.

**Comment by newAM** [comment]
Small update, still working on this; I am trying to find a cross-platform solution to unpack the DMG so that I can support this long-term when the vendor pushes an update, because the vendor only provides the OSX source in a DMG.

so far I have tried 7z, dmg2img, and hfsutils; but none of them produce anything useful from the vendor's DMG file.

**Comment by EncinitasMechanic** [comment]
I will look around, too.

I have been working with making the bindgen work. I can confirm that it works on Intel macs when the files are in the correct place, and can cross compile on arm macs with pregenerated bindings.  I cannot, however, make cross compiling on the arm macs work with bindgen. I get a error that it cannot find the ftd2xx.h.  I suspect that it is a sysroot issue, from what I can tell, but I have not been able to find a fix.

Haste and lack of git experience lead to me messing up my branch this morning, and I haven’t had time to sort it out yet, which put a bit of a damper of my plans to work on it today.

**Comment by EncinitasMechanic** [comment]
I ran the strings command on that DMG and found that it is formatted in APFS.  I confirmed that on my mac.  I tried to use libfsapfs to open it, but with no success so far

**Comment by EncinitasMechanic** [comment]
Sorry for all comments at once, but I keep getting unexpected free moments.  I was able to get the DMG mounted and files accessed on Linux using [APFS-Fuse](https://github.com/sgan81/apfs-fuse)

**Comment by newAM** [comment]
What arguments did you use for apfs-fuse?

There's no specific docs for mounting DMGs, but it seems like this _should_ work:
```txt
$ ./apfs-fuse -o uid="$(id -u)",gid="$(id -g)",allow_other ~/dl/D2XX1.4.16.dmg d2xx  
This doesn't seem to be an apfs volume (invalid superblock).
Unable to load container.
```

**Comment by EncinitasMechanic** [comment]
sudo ./apfs-fuse D2XX.1.4.24.dmg ../tmp

i appear to be using a newer DMG as well

**Comment by newAM** [comment]
Ahhh, that worked, `apfs-fuse` did not like the relative paths.

Good catch on the version!

**Comment by newAM** [comment]
I got this working in #32; static linking seems to be hitting a rust bug right now: https://github.com/rust-lang/rust/issues/50220

Dynamic linking seems to work though.

**Pull request closed without merging**
